version: "3.8"

services:

  client-frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - app

  app:
    build: .
    ports:
      - 8080:8080