spring:
  datasource:
    url: jdbc:postgresql://postgresdb/private
    username: pgadmin
    password: qwerasdf
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update