version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
    networks:
      - app-network
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:14.0-alpine
    container_name: postgres_db
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234qwer
      - POSTGRES_DB=private
