version: "3.8"

services:
  postgresdb:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=1234qwer
      - POSTGRES_DB=notes
    ports:
      - 5432:5432
  app:
    depends_on:
      - postgresdb
    build: .
    env_file: ./.env
    ports:
      - 8080:8080
    # environment:
    #   SPRING_APPLICATION_JSON: '{
    #     "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/notes",
    #     "spring.datasource.username" : "pgadmin",
    #     "spring.datasource.password" : "1234qwer",
    #     "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
    #     "spring.jpa.hibernate.ddl-auto" : "update"
    #   }'