version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:14.3-alpha
    environment:
      POSTGRES_DB: "provate"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234qwer"
    ports:
      - "5432:5432"